auth:
  reddit:
    bot:
    username: ${news.redditUser:?news.redditUser env variable not set}
    password: ${news.redditPW:?news.redditPW env variable not set}
    client:
      id: ${news.redditClientID:?news.redditClientID env variable not set}
      secret: ${news.redditSecret:?news.redditSecret env variable not set}